@baseUrl = http://localhost:3333/api/dashboard
@userId = user_2qtGOJ0U5rFqKz0QEqWU7THHnxE
@month = 12
@year = 2024

### @name latestTransactions
GET {{baseUrl}}/getDashboardData/{{userId}}/{{month}}/{{year}} HTTP/1.1
Content-Type: application/json