@baseUrl = http://localhost:3333/api/transaction
@userId = user_2qtGOJ0U5rFqKz0QEqWU7THHnxE 
@month = 1
@year = 2025

@transactionId = 6775b649c5bdb4b92d90c2a8

### @name create
POST {{baseUrl}}/create HTTP/1.1
Content-Type: application/json

{
  "userId": "user1",
  "description": "Compra de alimentos",
  "type": "expense",
  "categoryId": "6770771cc17997f992afcac8",
  "date": "2024-12-27T00:00:00.000Z",
  "value": 150.75
}

### @name update
PUT {{baseUrl}}/update/{{transactionId}} HTTP/1.1
Content-Type: application/json

{
  "description": "Compra de alimentos 2",
  "type": "expense",
  "categoryId": "6770771cc17997f992afcac8",
  "date": "2024-12-27T00:00:00.000Z",
  "value": 150.75
}

### @name delete 
DELETE {{baseUrl}}/delete/{{transactionId}} HTTP/1.1

### @name getAllByMonthAndYear
GET {{baseUrl}}/getAllByMonthAndYear/{{userId}}/{{month}}/{{year}} HTTP/1.1
