@baseUrl = http://localhost:3333/api/transaction
@userId = user_2qVVlDGin6xSOuFm7P5VOIoPMYi 

### @name create
POST {{baseUrl}}/create HTTP/1.1
Content-Type: application/json

{
  "userId": "user1",
  "description": "Compra de alimentos",
  "type": "expense",
  "categoryId": "6770771cc17997f992afcac8",
  "date": "2024-12-27T00:00:00.000Z",
  "value": 150.75
}
