@baseUrl = http://localhost:3333/api/user

### @name create
POST {{baseUrl}}/create HTTP/1.1
Content-Type: application/json

{
  "userId": "user1aaaaa3",
  "name": "User 1",
  "email": "dHs5j@example.comd",
  "photo": "https://example.com/photo.jpg"
}
